### ISSUE TITLE
GeoLite2 database no longer publicly available

### ISSUE THREAD

**Issue by erwanlr** [pwnlandia/mhn#738]
After a fresh install via git on an Ubuntu 18.04.3, the `sudo supervisorctl status` shows the below:

```
geoloc                           FATAL     Exited too quickly (process log may have details)
honeymap                         RUNNING   pid 30241, uptime 0:46:22
hpfeeds-broker                   RUNNING   pid 11140, uptime 0:51:49
mhn-celery-beat                  RUNNING   pid 31964, uptime 0:36:16
mhn-celery-worker                RUNNING   pid 32040, uptime 0:35:13
mhn-collector                    RUNNING   pid 31966, uptime 0:36:16
mhn-uwsgi                        RUNNING   pid 31968, uptime 0:36:16
mnemosyne                        RUNNING   pid 29382, uptime 0:50:14
```

The `/var/log/mhn/geoloc.err` contains:

```
Parsing config file: /opt/hpfeeds/geoloc.json
Traceback (most recent call last):
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 118, in <module>
    try: sys.exit(main())
  File "/opt/hpfeeds/examples/geoloc/geoloc.py", line 71, in main
    gi = geoip2.database.Reader("/opt/GeoLite2-City.mmdb")
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/geoip2/database.py", line 85, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/maxminddb/__init__.py", line 41, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/opt/hpfeeds/env/local/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, 'rb') as db_file:
IOError: [Errno 2] No such file or directory: '/opt/GeoLite2-City.mmdb'
```

After investigation, the TAR dowloaded by `install_honeymap.sh` are empty files, as https://geolite.maxmind.com/ does not seem to be up anymore:
- https://github.com/pwnlandia/mhn/blob/master/scripts/install_honeymap.sh#L93
- https://github.com/pwnlandia/mhn/blob/master/scripts/install_honeymap.sh#L97

```
sudo wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -O GeoLite2-City.tar.gz
--2020-01-01 23:45:55--  https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: No address associated with hostname.
wget: unable to resolve host address ‘geolite.maxmind.com’
```

As a result, the files needed (GeoLite2-City.mmdb and GeoLite2-ASN.mmdb) are not there.

Btw, the `geoloc.json` generated config (https://github.com/pwnlandia/mhn/blob/master/scripts/install_honeymap.sh#L110-L125) is also missing two channels compared to the ones present in the MongoDB: `kippo.alerts` and `cowrie.alerts`

**Comment by d1str0** [comment]
Max mind just changed their distribution method and license. I haven’t decided how to go about solving this. Perhaps just downloading and committing to the repo.

**Comment by zw1068** [comment]
I have a similar problem.
save us,please.

ubuntu18.04，fresh install.
I executed the script
`sudo ./install.sh`
when I finish 'MHN Configuration'，Program error：
IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'

`===========================================================
+ echo '  MHN Configuration'
  MHN Configuration
+ echo ===========================================================
===========================================================
+ python generateconfig.py
Do you wish to run in Debug mode?: y/n n
Superuser email: formyhonor@163.com
Superuser password: 
Superuser password: (again): 
Passwords did not match. Try again
Superuser password: 
Superuser password: (again): 
Server base url ["http://117.14.9.149"]: http://192.168.1.9
Honeymap url ["http://192.168.1.9:3000"]: 
Mail server address ["localhost"]: 
Mail server port [25]: 
Use TLS for email?: y/n y
Use SSL for email?: y/n y
Mail server username [""]: 
Mail server password [""]: 
Mail default sender [""]: 
Path for log file ["/var/log/mhn/mhn.log"]: 
+ echo -e '\nInitializing database, please be patient. This can take several minutes'

Initializing database, please be patient. This can take several minutes
+ python initdatabase.py
Traceback (most recent call last):
  File "initdatabase.py", line 1, in <module>
    from mhn import create_clean_db
  File "/opt/mhn/server/mhn/__init__.py", line 42, in <module>
    from mhn.ui.views import ui
  File "/opt/mhn/server/mhn/ui/views.py", line 10, in <module>
    from mhn.ui.utils import get_flag_ip, get_sensor_name
  File "/opt/mhn/server/mhn/ui/utils.py", line 15, in <module>
    geoip2_reader = geoip2.database.Reader(MHN_SERVER_HOME+'/../../GeoLite2-City.mmdb')
  File "/opt/mhn/env/local/lib/python2.7/site-packages/geoip2/database.py", line 86, in __init__
    self._db_reader = maxminddb.open_database(fileish, mode)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/__init__.py", line 41, in open_database
    return maxminddb.reader.Reader(database, mode)
  File "/opt/mhn/env/local/lib/python2.7/site-packages/maxminddb/reader.py", line 51, in __init__
    with open(database, 'rb') as db_file:
IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb'
`

**Comment by zw1068** [comment]
thank you @d1str0 
I have not to use .
Can 有 tell me What should I do to ensure the smooth installation of mhn?

**Comment by borekon** [comment]
I uploaded a copy of the database to my server, if you want to download it directly with wget:
https://files.vivancos.eu/GeoLite2-City.mmdb

**Comment by zw1068** [comment]
> 
> 
> I uploaded a copy of the database to my server, if you want to download it directly with wget:
> https://files.vivancos.eu/GeoLite2-City.mmdb
> Edit: you have to copy it to /opt/ to make the script works

thanks a lot, I will try.

**Comment by zw1068** [comment]
my bro, can you uploaded GeoLite2-City.tar.gz and GeoLite2-ASN.tar.gz .
I think maybe I need them . @borekon

**Comment by borekon** [comment]
> my bro, can you uploaded GeoLite2-City.tar.gz and GeoLite2-ASN.tar.gz .
> or email to me :[formyhonor@163.com](mailto:formyhonor@163.com)
> I think maybe I need them . @borekon

Here you go 
https://files.vivancos.eu/GeoLite2-City.tar.gz

**Comment by zw1068** [comment]
> > my bro, can you uploaded GeoLite2-City.tar.gz and GeoLite2-ASN.tar.gz .
> > or email to me :[formyhonor@163.com](mailto:formyhonor@163.com)
> > I think maybe I need them . @borekon
> 
> Here you go
> https://files.vivancos.eu/GeoLite2-City.tar.gz

thank you for your help.
I have downloaded it，can you edit off my email address，It maybe not saf. my fault,hah

**Comment by borekon** [comment]
You can edit the post in github.

Cheers

On Jan 8, 2020 22:24, zw1068 <notifications@github.com> wrote:

my bro, can you uploaded GeoLite2-City.tar.gz and GeoLite2-ASN.tar.gz .
or email to me :formyhonor@163.com<mailto:formyhonor@163.com>
I think maybe I need them . @borekon<https://github.com/borekon>

Here you go
https://files.vivancos.eu/GeoLite2-City.tar.gz

thank you for your help.
I have downloaded it，can you edit off my email address，It maybe not saf. my fault,hah

**Comment by zw1068** [comment]
I means the emailaddress in your reply

>         my bro, can you uploaded GeoLite2-City.tar.gz and GeoLite2-ASN.tar.gz .
>         **or email to me :formyhonor@163.com**
>         I think maybe I need them . @borekon
> 
>     Here you go
>     https://files.vivancos.eu/GeoLite2-City.tar.gz
>

**Comment by zw1068** [comment]
I downloaded GeoLite2-City.tar.gz，It works well.
can you upload GeoLite2-ASN.tar.gz

**Comment by d1str0** [comment]
You can download the latest versions from Maxmind still, you just have to sign up for a free account.

**Comment by zw1068** [comment]
> 
> 
> You can download the latest versions from Maxmind still, you just have to sign up for a free account.

thanks a lot

**Comment by borekon** [comment]
Of course, but you cannot with wget and another scripts. I uploaded to my server because matomo/piwik downloads it for web statistics.

On Jan 8, 2020 23:13, Brady Sullivan <notifications@github.com> wrote:

You can download the latest versions from Maxmind still, you just have to sign up for a free account.

**Comment by borekon** [comment]
This issue can now be closed. @Pwnlandia created a [new repo](https://github.com/pwnlandia/geolite2) with all the files

**Comment by vincenthalter** [comment]
@borekon I reinstalled it with the new repo. Still the same problem...
*IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb

**Comment by borekon** [comment]
> 
> 
> @borekon I reinstalled it with the new repo. Still the same problem...
> *IOError: [Errno 2] No such file or directory: '/opt/mhn/server/../../GeoLite2-City.mmdb

where did u put the downloaded file? it should be in /opt/

**Comment by axeII** [comment]
@vincenthalter I had same issue and the cause is that when you try to install `mhn` again it will just replace tar files with empty ones again. To fix this issue I had to comment lines in file `install_honeymap.sh`:

```
#wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz -O GeoLite2-City.tar.gz
#wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz -O GeoLite2-ASN.tar.gz
```

@borekon Thanks for those map data 👍

**Comment by erwanlr** [comment]
This has been fixed via https://github.com/pwnlandia/mhn/commit/f43b0c9178b08fae39c5fbac610e934e0a8e3b96

**Comment by domcia0600** [comment]
This issue is still persistent even with the newly updated file ^ 
install_honeymap.sh
wget https://github.com/pwnlandia/geolite2/raw/master/GeoLite2-City.tar.gz -O GeoLite2-City.tar.gz
